//
// Created by quantum on 6/16/21.
//

#ifndef CLAYENGINE_MOUSEBUTTONCODES_H
#define CLAYENGINE_MOUSEBUTTONCODES_H

#define CLAY_MOUSE_BUTTON_1         0
#define CLAY_MOUSE_BUTTON_2         1
#define CLAY_MOUSE_BUTTON_3         2
#define CLAY_MOUSE_BUTTON_4         3
#define CLAY_MOUSE_BUTTON_5         4
#define CLAY_MOUSE_BUTTON_6         5
#define CLAY_MOUSE_BUTTON_7         6
#define CLAY_MOUSE_BUTTON_8         7
#define CLAY_MOUSE_BUTTON_LAST      CLAY_MOUSE_BUTTON_8
#define CLAY_MOUSE_BUTTON_LEFT      CLAY_MOUSE_BUTTON_1
#define CLAY_MOUSE_BUTTON_RIGHT     CLAY_MOUSE_BUTTON_2
#define CLAY_MOUSE_BUTTON_MIDDLE    CLAY_MOUSE_BUTTON_3

#endif //CLAYENGINE_MOUSEBUTTONCODES_H
